In [1]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
csv_file_path_3 = '/content/drive/MyDrive/Major_Project/Utility_Matrices/Utility_Matrix_5000_0.8.csv'
df_user = pd.read_csv(csv_file_path_3,index_col=0)
df_user.head()

Manali  Leh Ladakh  Coorg  Andaman  Lakshadweep  Goa  Udaipur  \
Users                                                                   
user_0     0.0         1.0    4.0      3.0          5.0  1.0      3.0   
user_1     2.0         2.0    3.0      5.0          1.0  4.0      5.0   
user_2     4.0         4.0    3.0      5.0          2.0  4.0      4.0   
user_3     4.0         2.0    1.0      2.0          3.0  1.0      2.0   
user_4     1.0         0.0    1.0      1.0          5.0  5.0      1.0   

        Srinagar  Gangtok  Munnar  ...  Bikaner  Shimoga (Shivamogga)  \
Users                              ...                                  
user_0       3.0      0.0     0.0  ...      0.0                   2.0   
user_1       5.0      4.0     2.0  ...      0.0                   1.0   
user_2       3.0      5.0     3.0  ...      1.0                   4.0   
user_3       1.0      5.0     5.0  ...      1.0                   3.0   
user_4       3.0      4.0     1.0  ...      3.0                   5.0   

        Hogenakkal  Gir National Park  Kasauli  Pushkar  Chittorgarh  Nahan  \
Users                                                                         
user_0         3.0                1.0      2.0      2.0          5.0    4.0   
user_1         4.0                1.0      2.0      3.0          2.0    3.0   
user_2         0.0                1.0      1.0      3.0          1.0    5.0   
user_3         5.0                1.0      1.0      3.0          0.0    1.0   
user_4         3.0                2.0      4.0      0.0          5.0    2.0   

        Lavasa  Poovar  
Users                   
user_0     4.0     4.0  
user_1     3.0     0.0  
user_2     4.0     0.0  
user_3     4.0     0.0  
user_4     3.0     2.0  

[5 rows x 100 columns]

In [4]:
df_user = df_user.fillna(0)
df_user

Manali  Leh Ladakh  Coorg  Andaman  Lakshadweep  Goa  Udaipur  \
Users                                                                      
user_0        0.0         1.0    4.0      3.0          5.0  1.0      3.0   
user_1        2.0         2.0    3.0      5.0          1.0  4.0      5.0   
user_2        4.0         4.0    3.0      5.0          2.0  4.0      4.0   
user_3        4.0         2.0    1.0      2.0          3.0  1.0      2.0   
user_4        1.0         0.0    1.0      1.0          5.0  5.0      1.0   
...           ...         ...    ...      ...          ...  ...      ...   
user_4995     0.0         0.0    2.0      5.0          5.0  2.0      4.0   
user_4996     5.0         3.0    4.0      0.0          3.0  3.0      0.0   
user_4997     0.0         1.0    4.0      1.0          5.0  0.0      0.0   
user_4998     2.0         2.0    1.0      0.0          1.0  5.0      2.0   
user_4999     1.0         4.0    4.0      5.0          5.0  2.0      1.0   

           Srinagar  Gangtok  Munnar  ...  Bikaner  Shimoga (Shivamogga)  \
Users                                 ...                                  
user_0          3.0      0.0     0.0  ...      0.0                   2.0   
user_1          5.0      4.0     2.0  ...      0.0                   1.0   
user_2          3.0      5.0     3.0  ...      1.0                   4.0   
user_3          1.0      5.0     5.0  ...      1.0                   3.0   
user_4          3.0      4.0     1.0  ...      3.0                   5.0   
...             ...      ...     ...  ...      ...                   ...   
user_4995       4.0      1.0     3.0  ...      2.0                   5.0   
user_4996       1.0      5.0     0.0  ...      0.0                   0.0   
user_4997       3.0      2.0     1.0  ...      4.0                   2.0   
user_4998       1.0      3.0     4.0  ...      3.0                   1.0   
user_4999       1.0      4.0     4.0  ...      0.0                   3.0   

           Hogenakkal  Gir National Park  Kasauli  Pushkar  Chittorgarh  \
Users                                                                     
user_0            3.0                1.0      2.0      2.0          5.0   
user_1            4.0                1.0      2.0      3.0          2.0   
user_2            0.0                1.0      1.0      3.0          1.0   
user_3            5.0                1.0      1.0      3.0          0.0   
user_4            3.0                2.0      4.0      0.0          5.0   
...               ...                ...      ...      ...          ...   
user_4995         4.0                1.0      1.0      0.0          0.0   
user_4996         0.0                5.0      4.0      3.0          3.0   
user_4997         4.0                0.0      1.0      3.0          2.0   
user_4998         3.0                0.0      0.0      2.0          3.0   
user_4999         4.0                3.0      5.0      2.0          1.0   

           Nahan  Lavasa  Poovar  
Users                             
user_0       4.0     4.0     4.0  
user_1       3.0     3.0     0.0  
user_2       5.0     4.0     0.0  
user_3       1.0     4.0     0.0  
user_4       2.0     3.0     2.0  
...          ...     ...     ...  
user_4995    2.0     0.0     4.0  
user_4996    5.0     2.0     3.0  
user_4997    0.0     3.0     5.0  
user_4998    0.0     3.0     3.0  
user_4999    4.0     4.0     3.0  

[5000 rows x 100 columns]

In [5]:
num_clusters = 2
kmeans = KMeans(n_clusters=num_clusters)
df_user_np = df_user
kmeans.fit(df_user_np)

# Assigning cluster labels to items
item_clusters = kmeans.labels_
print(item_clusters)

# Finding the centroid of each cluster
cluster_centers = kmeans.cluster_centers_

cluster_centers

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


[0 0 0 ... 1 0 0]


array([[2.53038229, 2.64185111, 2.50704225, 2.31146881, 2.34607646,
        2.56700201, 2.29859155, 2.19637827, 2.39879276, 2.49416499,
        2.3806841 , 2.50261569, 2.22374245, 2.33802817, 2.10100604,
        2.41851107, 2.23822938, 2.29899396, 2.44104628, 2.19879276,
        2.29014085, 2.26197183, 2.7110664 , 2.31911469, 2.50744467,
        2.16418511, 2.35935614, 2.86519115, 2.16136821, 2.16820926,
        2.47565392, 2.69979879, 2.41126761, 2.20160966, 2.28692153,
        2.54245473, 2.69416499, 2.55694165, 2.66277666, 2.61408451,
        2.08249497, 2.36820926, 2.30663984, 2.3943662 , 2.4249497 ,
        2.27967807, 2.36177062, 2.29979879, 2.57625755, 2.33440644,
        2.43138833, 2.33279678, 2.29657948, 2.23460765, 2.5915493 ,
        2.22253521, 2.46358149, 2.29818913, 2.60925553, 2.35895372,
        2.66921529, 2.49215292, 2.04708249, 2.37545272, 2.10704225,
        2.47484909, 2.43138833, 2.54849095, 2.18712274, 2.54808853,
        2.45593561, 2.22977867, 2.35090543, 2.13

In [ ]:
def euclidean_distance(point1, point2):
    point1 = np.array(point1)
    point2 = np.array(point2)
    squared_diff = (point1 - point2) ** 2
    distance = np.sqrt(np.sum(squared_diff))
    return distance

def recommend_user(user_ratings):
    distances = [euclidean_distance(user_ratings, point) for point in cluster_centers]
    print(distances)

    # Find the cluster with the minimum distance
    cluster_index = np.argmin(distances)
    print(cluster_index)


    # Items in the closest cluster are potential recommendations
    recommended_items = np.where(item_clusters == cluster_index)[0]

    return recommended_items

print(recommend_user(np.array([1,0,3,4,1])))



[3.9581140290126386, 6.304760106459246]
0
[1 2 3]
